package edu.pitt.dbmi.deepphe.summarization.orm.i2b2data;

// Generated Apr 15, 2015 4:30:25 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObservationFactId generated by hbm2java
 */
@Embeddable
public class ObservationFactId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private BigDecimal patientNum;
	private String conceptCd;
	private String modifierCd;
	private Date startDate;
	private BigDecimal encounterNum;
	private long instanceNum;
	private String providerId;

	public ObservationFactId() {
	}

	public ObservationFactId(BigDecimal patientNum, String conceptCd,
			String modifierCd, Date startDate, BigDecimal encounterNum,
			long instanceNum, String providerId) {
		this.patientNum = patientNum;
		this.conceptCd = conceptCd;
		this.modifierCd = modifierCd;
		this.startDate = startDate;
		this.encounterNum = encounterNum;
		this.instanceNum = instanceNum;
		this.providerId = providerId;
	}

	@Column(name = "PATIENT_NUM", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPatientNum() {
		return this.patientNum;
	}

	public void setPatientNum(BigDecimal patientNum) {
		this.patientNum = patientNum;
	}

	@Column(name = "CONCEPT_CD", nullable = false, length = 50)
	public String getConceptCd() {
		return this.conceptCd;
	}

	public void setConceptCd(String conceptCd) {
		this.conceptCd = conceptCd;
	}

	@Column(name = "MODIFIER_CD", nullable = false, length = 100)
	public String getModifierCd() {
		return this.modifierCd;
	}

	public void setModifierCd(String modifierCd) {
		this.modifierCd = modifierCd;
	}

	@Column(name = "START_DATE", nullable = false, length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "ENCOUNTER_NUM", nullable = false, precision = 38, scale = 0)
	public BigDecimal getEncounterNum() {
		return this.encounterNum;
	}

	public void setEncounterNum(BigDecimal encounterNum) {
		this.encounterNum = encounterNum;
	}

	@Column(name = "INSTANCE_NUM", nullable = false, precision = 18, scale = 0)
	public long getInstanceNum() {
		return this.instanceNum;
	}

	public void setInstanceNum(long instanceNum) {
		this.instanceNum = instanceNum;
	}

	@Column(name = "PROVIDER_ID", nullable = false, length = 50)
	public String getProviderId() {
		return this.providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObservationFactId))
			return false;
		ObservationFactId castOther = (ObservationFactId) other;

		return ((this.getPatientNum() == castOther.getPatientNum()) || (this
				.getPatientNum() != null && castOther.getPatientNum() != null && this
				.getPatientNum().equals(castOther.getPatientNum())))
				&& ((this.getConceptCd() == castOther.getConceptCd()) || (this
						.getConceptCd() != null
						&& castOther.getConceptCd() != null && this
						.getConceptCd().equals(castOther.getConceptCd())))
				&& ((this.getModifierCd() == castOther.getModifierCd()) || (this
						.getModifierCd() != null
						&& castOther.getModifierCd() != null && this
						.getModifierCd().equals(castOther.getModifierCd())))
				&& ((this.getStartDate() == castOther.getStartDate()) || (this
						.getStartDate() != null
						&& castOther.getStartDate() != null && this
						.getStartDate().equals(castOther.getStartDate())))
				&& ((this.getEncounterNum() == castOther.getEncounterNum()) || (this
						.getEncounterNum() != null
						&& castOther.getEncounterNum() != null && this
						.getEncounterNum().equals(castOther.getEncounterNum())))
				&& (this.getInstanceNum() == castOther.getInstanceNum())
				&& ((this.getProviderId() == castOther.getProviderId()) || (this
						.getProviderId() != null
						&& castOther.getProviderId() != null && this
						.getProviderId().equals(castOther.getProviderId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPatientNum() == null ? 0 : this.getPatientNum()
						.hashCode());
		result = 37 * result
				+ (getConceptCd() == null ? 0 : this.getConceptCd().hashCode());
		result = 37
				* result
				+ (getModifierCd() == null ? 0 : this.getModifierCd()
						.hashCode());
		result = 37 * result
				+ (getStartDate() == null ? 0 : this.getStartDate().hashCode());
		result = 37
				* result
				+ (getEncounterNum() == null ? 0 : this.getEncounterNum()
						.hashCode());
		result = 37 * result + (int) this.getInstanceNum();
		result = 37
				* result
				+ (getProviderId() == null ? 0 : this.getProviderId()
						.hashCode());
		return result;
	}

}
