package edu.pitt.dbmi.deepphe.summarization.orm.i2b2data;

// Generated Apr 15, 2015 4:30:25 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProviderDimensionId generated by hbm2java
 */
@Embeddable
public class ProviderDimensionId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String providerPath;
	private String providerId;

	public ProviderDimensionId() {
	}

	public ProviderDimensionId(String providerPath, String providerId) {
		this.providerPath = providerPath;
		this.providerId = providerId;
	}

	@Column(name = "PROVIDER_PATH", nullable = false, length = 700)
	public String getProviderPath() {
		return this.providerPath;
	}

	public void setProviderPath(String providerPath) {
		this.providerPath = providerPath;
	}

	@Column(name = "PROVIDER_ID", nullable = false, length = 50)
	public String getProviderId() {
		return this.providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProviderDimensionId))
			return false;
		ProviderDimensionId castOther = (ProviderDimensionId) other;

		return ((this.getProviderPath() == castOther.getProviderPath()) || (this
				.getProviderPath() != null
				&& castOther.getProviderPath() != null && this
				.getProviderPath().equals(castOther.getProviderPath())))
				&& ((this.getProviderId() == castOther.getProviderId()) || (this
						.getProviderId() != null
						&& castOther.getProviderId() != null && this
						.getProviderId().equals(castOther.getProviderId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProviderPath() == null ? 0 : this.getProviderPath()
						.hashCode());
		result = 37
				* result
				+ (getProviderId() == null ? 0 : this.getProviderId()
						.hashCode());
		return result;
	}

}
