package edu.pitt.dbmi.deepphe.summarization.orm.i2b2meta;

// Generated Apr 29, 2015 4:35:02 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeeppheOntology generated by hbm2java
 */
@Entity
@Table(name = "DEEPPHE_ONTOLOGY", schema = "I2B2METADATA")
public class DeeppheOntology implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String CFullname;
	private BigDecimal CHlevel;
	private String CName;
	private String CSynonymCd;
	private String CVisualattributes;
	private BigDecimal CTotalnum;
	private String CBasecode;
	private Clob CMetadataxml;
	private String CFacttablecolumn;
	private String CTablename;
	private String CColumnname;
	private String CColumndatatype;
	private String COperator;
	private String CDimcode;
	private Clob CComment;
	private String CTooltip;
	private String MAppliedPath;
	private Date updateDate;
	private Date downloadDate;
	private Date importDate;
	private String sourcesystemCd;
	private String valuetypeCd;
	private String MExclusionCd;
	private String CPath;
	private String CSymbol;

	public DeeppheOntology() {
	}

	public DeeppheOntology(String CFullname) {
		this.CFullname = CFullname;
	}

	public DeeppheOntology(String CFullname, BigDecimal CHlevel, String CName,
			String CSynonymCd, String CVisualattributes, BigDecimal CTotalnum,
			String CBasecode, Clob CMetadataxml, String CFacttablecolumn,
			String CTablename, String CColumnname, String CColumndatatype,
			String COperator, String CDimcode, Clob CComment, String CTooltip,
			String MAppliedPath, Date updateDate, Date downloadDate,
			Date importDate, String sourcesystemCd, String valuetypeCd,
			String MExclusionCd, String CPath, String CSymbol) {
		this.CFullname = CFullname;
		this.CHlevel = CHlevel;
		this.CName = CName;
		this.CSynonymCd = CSynonymCd;
		this.CVisualattributes = CVisualattributes;
		this.CTotalnum = CTotalnum;
		this.CBasecode = CBasecode;
		this.CMetadataxml = CMetadataxml;
		this.CFacttablecolumn = CFacttablecolumn;
		this.CTablename = CTablename;
		this.CColumnname = CColumnname;
		this.CColumndatatype = CColumndatatype;
		this.COperator = COperator;
		this.CDimcode = CDimcode;
		this.CComment = CComment;
		this.CTooltip = CTooltip;
		this.MAppliedPath = MAppliedPath;
		this.updateDate = updateDate;
		this.downloadDate = downloadDate;
		this.importDate = importDate;
		this.sourcesystemCd = sourcesystemCd;
		this.valuetypeCd = valuetypeCd;
		this.MExclusionCd = MExclusionCd;
		this.CPath = CPath;
		this.CSymbol = CSymbol;
	}

	@Id
	@Column(name = "C_FULLNAME", unique = true, nullable = false, length = 2100)
	public String getCFullname() {
		return this.CFullname;
	}

	public void setCFullname(String CFullname) {
		this.CFullname = CFullname;
	}

	@Column(name = "C_HLEVEL", precision = 22, scale = 0)
	public BigDecimal getCHlevel() {
		return this.CHlevel;
	}

	public void setCHlevel(BigDecimal CHlevel) {
		this.CHlevel = CHlevel;
	}

	@Column(name = "C_NAME", length = 4000)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Column(name = "C_SYNONYM_CD", length = 3)
	public String getCSynonymCd() {
		return this.CSynonymCd;
	}

	public void setCSynonymCd(String CSynonymCd) {
		this.CSynonymCd = CSynonymCd;
	}

	@Column(name = "C_VISUALATTRIBUTES", length = 9)
	public String getCVisualattributes() {
		return this.CVisualattributes;
	}

	public void setCVisualattributes(String CVisualattributes) {
		this.CVisualattributes = CVisualattributes;
	}

	@Column(name = "C_TOTALNUM", precision = 22, scale = 0)
	public BigDecimal getCTotalnum() {
		return this.CTotalnum;
	}

	public void setCTotalnum(BigDecimal CTotalnum) {
		this.CTotalnum = CTotalnum;
	}

	@Column(name = "C_BASECODE", length = 150)
	public String getCBasecode() {
		return this.CBasecode;
	}

	public void setCBasecode(String CBasecode) {
		this.CBasecode = CBasecode;
	}

	@Column(name = "C_METADATAXML")
	public Clob getCMetadataxml() {
		return this.CMetadataxml;
	}

	public void setCMetadataxml(Clob CMetadataxml) {
		this.CMetadataxml = CMetadataxml;
	}

	@Column(name = "C_FACTTABLECOLUMN", length = 150)
	public String getCFacttablecolumn() {
		return this.CFacttablecolumn;
	}

	public void setCFacttablecolumn(String CFacttablecolumn) {
		this.CFacttablecolumn = CFacttablecolumn;
	}

	@Column(name = "C_TABLENAME", length = 150)
	public String getCTablename() {
		return this.CTablename;
	}

	public void setCTablename(String CTablename) {
		this.CTablename = CTablename;
	}

	@Column(name = "C_COLUMNNAME", length = 150)
	public String getCColumnname() {
		return this.CColumnname;
	}

	public void setCColumnname(String CColumnname) {
		this.CColumnname = CColumnname;
	}

	@Column(name = "C_COLUMNDATATYPE", length = 150)
	public String getCColumndatatype() {
		return this.CColumndatatype;
	}

	public void setCColumndatatype(String CColumndatatype) {
		this.CColumndatatype = CColumndatatype;
	}

	@Column(name = "C_OPERATOR", length = 30)
	public String getCOperator() {
		return this.COperator;
	}

	public void setCOperator(String COperator) {
		this.COperator = COperator;
	}

	@Column(name = "C_DIMCODE", length = 2100)
	public String getCDimcode() {
		return this.CDimcode;
	}

	public void setCDimcode(String CDimcode) {
		this.CDimcode = CDimcode;
	}

	@Column(name = "C_COMMENT")
	public Clob getCComment() {
		return this.CComment;
	}

	public void setCComment(Clob CComment) {
		this.CComment = CComment;
	}

	@Column(name = "C_TOOLTIP", length = 2700)
	public String getCTooltip() {
		return this.CTooltip;
	}

	public void setCTooltip(String CTooltip) {
		this.CTooltip = CTooltip;
	}

	@Column(name = "M_APPLIED_PATH", length = 2100)
	public String getMAppliedPath() {
		return this.MAppliedPath;
	}

	public void setMAppliedPath(String MAppliedPath) {
		this.MAppliedPath = MAppliedPath;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOWNLOAD_DATE", length = 7)
	public Date getDownloadDate() {
		return this.downloadDate;
	}

	public void setDownloadDate(Date downloadDate) {
		this.downloadDate = downloadDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPORT_DATE", length = 7)
	public Date getImportDate() {
		return this.importDate;
	}

	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	@Column(name = "SOURCESYSTEM_CD", length = 150)
	public String getSourcesystemCd() {
		return this.sourcesystemCd;
	}

	public void setSourcesystemCd(String sourcesystemCd) {
		this.sourcesystemCd = sourcesystemCd;
	}

	@Column(name = "VALUETYPE_CD", length = 150)
	public String getValuetypeCd() {
		return this.valuetypeCd;
	}

	public void setValuetypeCd(String valuetypeCd) {
		this.valuetypeCd = valuetypeCd;
	}

	@Column(name = "M_EXCLUSION_CD", length = 75)
	public String getMExclusionCd() {
		return this.MExclusionCd;
	}

	public void setMExclusionCd(String MExclusionCd) {
		this.MExclusionCd = MExclusionCd;
	}

	@Column(name = "C_PATH", length = 2100)
	public String getCPath() {
		return this.CPath;
	}

	public void setCPath(String CPath) {
		this.CPath = CPath;
	}

	@Column(name = "C_SYMBOL", length = 150)
	public String getCSymbol() {
		return this.CSymbol;
	}

	public void setCSymbol(String CSymbol) {
		this.CSymbol = CSymbol;
	}

}
