package edu.pitt.dbmi.deepphe.summarization.orm.i2b2meta;
// Generated Apr 29, 2015 4:35:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OntProcessStatus generated by hbm2java
 */
@Entity
@Table(name="ONT_PROCESS_STATUS"
    ,schema="I2B2METADATA"
)
public class OntProcessStatus  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int processId;
     private String processTypeCd;
     private Date startDate;
     private Date endDate;
     private String processStepCd;
     private String processStatusCd;
     private BigDecimal crcUploadId;
     private String statusCd;
     private Clob message;
     private Date entryDate;
     private Date changeDate;
     private String changedbyChar;

    public OntProcessStatus() {
    }

	
    public OntProcessStatus(int processId) {
        this.processId = processId;
    }
    public OntProcessStatus(int processId, String processTypeCd, Date startDate, Date endDate, String processStepCd, String processStatusCd, BigDecimal crcUploadId, String statusCd, Clob message, Date entryDate, Date changeDate, String changedbyChar) {
       this.processId = processId;
       this.processTypeCd = processTypeCd;
       this.startDate = startDate;
       this.endDate = endDate;
       this.processStepCd = processStepCd;
       this.processStatusCd = processStatusCd;
       this.crcUploadId = crcUploadId;
       this.statusCd = statusCd;
       this.message = message;
       this.entryDate = entryDate;
       this.changeDate = changeDate;
       this.changedbyChar = changedbyChar;
    }
   
     @Id 

    
    @Column(name="PROCESS_ID", unique=true, nullable=false, precision=5, scale=0)
    public int getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(int processId) {
        this.processId = processId;
    }

    
    @Column(name="PROCESS_TYPE_CD", length=50)
    public String getProcessTypeCd() {
        return this.processTypeCd;
    }
    
    public void setProcessTypeCd(String processTypeCd) {
        this.processTypeCd = processTypeCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=7)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="PROCESS_STEP_CD", length=50)
    public String getProcessStepCd() {
        return this.processStepCd;
    }
    
    public void setProcessStepCd(String processStepCd) {
        this.processStepCd = processStepCd;
    }

    
    @Column(name="PROCESS_STATUS_CD", length=50)
    public String getProcessStatusCd() {
        return this.processStatusCd;
    }
    
    public void setProcessStatusCd(String processStatusCd) {
        this.processStatusCd = processStatusCd;
    }

    
    @Column(name="CRC_UPLOAD_ID", precision=38, scale=0)
    public BigDecimal getCrcUploadId() {
        return this.crcUploadId;
    }
    
    public void setCrcUploadId(BigDecimal crcUploadId) {
        this.crcUploadId = crcUploadId;
    }

    
    @Column(name="STATUS_CD", length=50)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }

    
    @Column(name="MESSAGE")
    public Clob getMessage() {
        return this.message;
    }
    
    public void setMessage(Clob message) {
        this.message = message;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE", length=7)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CHANGE_DATE", length=7)
    public Date getChangeDate() {
        return this.changeDate;
    }
    
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }

    
    @Column(name="CHANGEDBY_CHAR", length=50)
    public String getChangedbyChar() {
        return this.changedbyChar;
    }
    
    public void setChangedbyChar(String changedbyChar) {
        this.changedbyChar = changedbyChar;
    }




}


